
import React from 'react';
import { Link } from 'react-router-dom';
import { Button } from '../components/Button';

export const About: React.FC = () => {
  return (
    <div className="min-h-screen pt-24 pb-20 px-4 md:px-8">
      <div className="max-w-4xl mx-auto bg-black/80 backdrop-blur-md p-8 md:p-12 rounded-3xl border border-white/10 shadow-2xl">
        <h1 className="text-4xl md:text-6xl font-black mb-8 text-center uppercase italic tracking-tighter drop-shadow-[0_0_15px_rgba(0,255,170,0.5)]">
          About <span className="text-neon">FaceExpo</span>
        </h1>

        <div className="space-y-6 text-lg text-gray-300 leading-relaxed mb-10 text-justify md:text-left">
          <p>
            <strong className="text-white">FaceExpo</strong> is a talent-discovery platform built to help real artists get seen, heard, and celebrated.
          </p>
          
          <p>
            We believe music is a human art form — something created from soul, passion, and lived experience — not generated by machines. Our mission is to give rising singers, musicians, and performers the spotlight they deserve in an industry that often overlooks new voices.
          </p>

          <p>
            Through community-driven contests, challenges, and ranking systems, FaceExpo gives every artist a way to level up and build a fanbase from day one. We connect songwriters with musicians, creators with collaborators, and talent with opportunity — turning raw potential into real careers.
          </p>

          <p>
            Whether you’re chasing a dream, building a brand, or looking for the next big star… FaceExpo was made for you.
          </p>

          <p className="text-2xl font-bold text-neon text-center pt-6 italic drop-shadow-md">
            Real Talent. Real Fans. Real Discovery.
          </p>
        </div>

        <div className="aspect-video w-full rounded-2xl overflow-hidden border-2 border-gray-800 shadow-[0_0_30px_rgba(0,0,0,0.5)] mb-10 group hover:border-neon/50 transition-colors duration-300">
          <iframe 
            className="w-full h-full"
            src="https://www.youtube.com/embed/a9EaAISiT5g?rel=0&playsinline=1&modestbranding=1" 
            title="FaceExpo Video" 
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
            allowFullScreen
          ></iframe>
        </div>

        <div className="flex justify-center pt-4">
            <Link to="/auth">
                <Button className="px-12 py-4 text-lg shadow-[0_0_20px_rgba(0,255,170,0.4)] hover:scale-105 transition-transform">
                    Join the Movement
                </Button>
            </Link>
        </div>
      </div>
    </div>
  );
};
